services:
  moto:
    container_name: ex_aws_configurator_moto
    image: motoserver/moto:4.2.14
    ports:
      - "4566:5000"
    environment:
      - MOTO_PORT=5000

  lib:
    container_name: ex_aws_configurator_lib
    depends_on:
      - moto
    volumes:
      - .:/app
    build:
      context: .
      target: dev
    command: tail -f /dev/null
