version: '3.7'

services:
  localstack:
    container_name: ex_aws_configurator_localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sns,sqs

  lib:
    container_name: ex_aws_configurator_lib
    depends_on:
      - localstack
    volumes:
      - .:/app
    build:
      context: .
      target: dev
    command: tail -f /dev/null
